version: "3"

services:
  spring:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - bash
      - -c
      - |
        java -jar /app.jar
    volumes:
      - .:/app/
    ports:
      - "8080:8080"